// Supported with union (c) 2020 Union team
// Union SOURCE file

#include<set>
namespace GOTHIC_ENGINE {
	auto const AIV_BOSS = 90;
	auto JSON_FILE_NAME = "punclev-utils.json";

	auto EXTRA_LOOT_BASE_CHANCE = 15;
	auto EXTRA_LOOT_HP_FACTOR_HORINIS = 400;
	auto EXTRA_LOOT_HP_FACTOR_OTHER = 700;
	auto EXTRA_LOOT_HP_FACTOR_MULTIPLIER = 25;
	auto EXTRA_LOOT_HORINIS_FACTOR = 1000;
	auto EXTRA_LOOT_OTHER_FACTOR = 1250;
	auto EXTRA_LOOT_CHEST_BASE_CHANCE = 450;

	auto EXTRA_LOOT_BASE_STRENGTH_PER_LOOT_MULTIPLIER = 1;
	auto EXTRA_LOOT_VALUE_STRENGTH_PER_LOOT_MULTIPLIER = 250;

	auto ENEMY_STATS_PER_MULTIPLIER = 25;
	auto ENEMY_DEFENCE_PER_MULTIPLIER = 3;
	auto ENEMY_HP_FACTOR = 150;

	auto SHOULD_ADD_LOOT_TO_PLAYER = FALSE;
	auto SHOULD_IGNORE_CHECK_TO_ADD_LOOT = FALSE;
	auto SHOULD_ADD_LOOT_TO_NPC = FALSE;
	auto SHOULD_ADD_LOOT_TO_CHESTS = FALSE;
	auto SHOULD_USE_NPC_LOOT_FOR_CHESTS = TRUE;
	auto IS_DEBUG = FALSE;

	int getExtraLootProbability(oCNpc* npc, oCWorld* world) {
		auto hpFactor = world->GetObjectName().HasWordI("NEWWORLD") ? EXTRA_LOOT_HP_FACTOR_HORINIS : EXTRA_LOOT_HP_FACTOR_OTHER;
		auto chance = EXTRA_LOOT_BASE_CHANCE + ((int)npc->attribute[NPC_ATR_HITPOINTSMAX] / hpFactor) * EXTRA_LOOT_HP_FACTOR_MULTIPLIER;

		return max(chance, 10);
	}
}